forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-ntp'
mod 'puppetlabs-mysql'
mod 'puppet-nginx'
mod 'puppetlabs-docker_platform'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-git'
mod 'Slashbunny-phpfpm'
mod 'puppet-archive'
