forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/ntp'
mod 'puppetlabs/mysql'
mod 'puppet/nginx'
mod 'garethr/docker'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/git'
mod 'Slashbunny/phpfpm'
mod 'puppet/archive'
