version: '2'
services:
  con_mysql:
    build:
      context: /vagrant/docker/database-image
      dockerfile: Dockerfile
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - .:/code

  con_php:
    build:
      context: /vagrant/docker/php-image
      dockerfile: Dockerfile
    image: phpfpm
    ports:
      - "9000:9000"
    depends_on:
      - con_mysql
    volumes:
      - /site
    external_links:
      - con_mysql

  con_nginx:
    build:
      context: /vagrant/docker/webserver-image
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - con_php
    volumes_from:
      - con_php
    external_links:
      - con_php
