FROM imgpuppet
MAINTAINER Ukbe Akdogan

ENV HOSTROLE=database

#COPY ./set_hosts.sh /tmp/

#RUN bash /tmp/set_hosts.sh

RUN echo 192.168.10.10 puppet.local >> /etc/hosts; cat /etc/hosts

RUN cat /etc/hosts

RUN puppet agent --enable

RUN puppet agent -t

# Revoke client certificate on Puppet server since
# we won't be accessing the Puppet server with this hostname
RUN curl --cert /etc/puppetlabs/puppet/ssl/certs/${HOSTNAME}.pem \
         --key /etc/puppetlabs/puppet/ssl/private_keys/${HOSTNAME}.pem \
         --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem \
         -X PUT -H "Content-Type: application/json" -d '{"desired_state":"revoked"}' \
         https://puppet.local:8140/puppet-ca/v1/certificate_status/${HOSTNAME}

# Delete client certificate on Puppet server since
RUN curl --cert /etc/puppetlabs/puppet/ssl/certs/${HOSTNAME}.pem \
         --key /etc/puppetlabs/puppet/ssl/private_keys/${HOSTNAME}.pem \
         --cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem \
         -X DELETE -d '{"desired_state":"revoked"}' \
         https://puppet.local:8140/puppet-ca/v1/certificate_status/${HOSTNAME}

# Delete client certificate and key on Puppet server since
RUN rm -rf /etc/puppetlabs/puppet/ssl

VOLUME /vagrant/vol-database/etc/mysql:/etc/mysql
VOLUME /vagrant/vol-database/var/lib/mysql:/var/lib/mysql
VOLUME /vagrant/vol-database/var/log/mysql:/var/log/mysql

EXPOSE 3306

CMD systemctl start mysql.service
